### ISSUE TITLE
hello there

### ISSUE THREAD

**Issue by lamersathucs** [onerri/java-bst#1]
![image](https://user-images.githubusercontent.com/50542164/57581759-bcb68100-74c4-11e9-91a7-4a3c17e09b9a.png)

https://www.youtube.com/watch?v=hbzARt3RLOk
Hala assignment olduğunu gösteren bir ibare göremedim.

**Comment by lamersathucs** [comment]
@onerri

**Comment by b21627342** [comment]
öyle bir şey görmen mi gerekiyor?ciddi sorunları olan birisin bu arada, üzüldüm senin adına

**Comment by onerri** [comment]
öyle bir şey görmen mi gerekiyor?ciddi sorunları olan birisin bu arada, üzüldüm senin adına @lamersathucs

**Comment by lamersathucs** [comment]
@onerri 
![image](https://user-images.githubusercontent.com/50542164/57582004-54699e80-74c8-11e9-81e6-44cbdca81271.png)

önce githubun nasıl kullanılacağını öğren, daha sonra hangi hesaptan yazman gerektiğini öğren ve daha da sonrasında open source camiasını öğren. Burada tek bir sorun var o da senin cahilliğin. Githubun içine sıçtınız. Artık insanların cvleri okunurken github linklerine basmaktan korkuyor şirketler. Boktan assignmentlarınızı da alın siktir olun gidin bu platformdan.

**Comment by onerri** [comment]
bak ben sana küfür etmedim edebini takın adam ol. burda herhangi bir şeyi düzgün yaptığımı iddia etmiyorum kimse anasının karnından bunları bilerek de çıkmıyor. Daha kendi adını verip konuşacak cesarete bile sahip olmayan özgüvensiz bi karaktersizin tekisin.

**Comment by onerri** [comment]
gtihub'ı ya da programlamayı bilmesem de çok şükür insanlara anonim olarak küfür edip salça olmayacak kadar terbiye ve ahlaka sahibim @lamersathucs

**Comment by lamersathucs** [comment]
tam da ben bundan bahsediyorum. programlamayı bilmiyorsan ee'nin puanı artık daha düşük geçebilirsin. bölüm sizin gibi puanı ee'ye yetmeyip bize kalan insanlarla dolu. 2016 girişlisin(programlama çalışmak için 1 senen vardı hazırlıkta) ve hala programlama bilmiyorum diyebiliyorsun. küfür konusuna gelirsem, şahsına küfür etmiyorum genel konuşuyorum. senin gibi yapan bir çok insan var.

programlamayı bilmiyorum diyerek seviyeni belli ettin zaten. senin seviyenle konuşuyorum merak etme. bu seviyede istediğime salça olurum. bu platformun amacı da budur. kodunu atarsın, buraya insanlar yorumlarını yazar, eklemeler yapar düzenlemeler önerir. ben de öneriyorum bak.

işin adabını söylüyorum. iyi dinle burayı. bir abin olarak benden de bir şeyler duy. ben bunları yazıyorsam diğer duydukların işe yaramamış demektir.

1(bir) adet repo açılır. ismini sen koy idfc. içine ders kodlarıyla klasör açarsın. assignment olduğunu belirtirsin. çözümlerini yaparsın. ve cvye oraya buraya yazmazsın, başlangıç noktasından geçip para da alamazsın.

**Comment by onerri** [comment]
kim ne okuyacak sen mi karar veriyorsun buna?hayatımın hiçbir noktasında programlama bildiğimi iddia edecek seviyeye geleceğimi düşnümüyorum. Belli ki ,sen çok biliyorsun ama gelmiş burda anonim hesaptan başkalarının işlerine burnunu sokuyorsun. Senin durumunun da pek iyi olduğu söylenemez. Hala adını verecek cesaretin yok gelmiş konuşuyorsun burada @lamersathucs
